
FROM node:22-alpine AS builder

WORKDIR /app
COPY package.json package-lock.json ./    
RUN npm ci                                

COPY . .
RUN npm run build                          

FROM nginx:stable-alpine AS runner

# Replace the default nginx site
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy the static files
COPY --from=builder /app/dist /usr/share/nginx/html

RUN mkdir -p /var/www/certbot

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
