INSERT INTO public.exercises (name, is_bodyweight, muscle_group_id, slug, is_time_based)
VALUES
-- Chest
    ('Bench Press', false, 1, 'bench-press', false),
    ('Incline Bench Press', false, 1, 'incline-bench-press', false),
    ('Incline Dumbbell Press', false, 1, 'incline-dumbbell-press', false),
    ('Dumbbell Flyes', false, 1, 'dumbbell-flyes', false),
    ('Cable Crossovers', false, 1, 'cable-crossovers', false),
    ('Chest Press Machine', false, 1, 'chest-press-machine', false),
    ('Pec Deck', false, 1, 'pec-deck', false),
    ('Push-Ups', true, 1, 'push-ups', false),
    ('Chest Dips', true, 1, 'chest-dips', false),
    ('Cable Flyes', false, 1, 'cable-flyes', false),
    ('Incline Cable Flyes', false, 1, 'incline-cable-flyes', false),
    ('Dumbbell Bench Press', false, 1, 'dumbbell-bench-press', false),
    ('Smith Machine Bench Press', false, 1, 'smith-machine-bench-press', false),
    ('Incline Smith Machine Press', false, 1, 'incline-smith-machine-press', false),
-- Back
    ('Barbell Rows', false, 2, 'barbell-rows', false),
    ('Pull-Ups', true, 2, 'pull-ups', false),
    ('Chin-Ups', true, 2, 'chin-ups', false),
    ('Lat Pulldowns', false, 2, 'lat-pulldowns', false),
    ('Pullovers', false, 2, 'pullovers', false),
    ('Narrow Grip Seated Cable Rows', false, 2, 'narrow-grip-seated-cable-rows', false),
    ('T-Bar Rows', false, 2, 't-bar-rows', false),
    ('Single Arm Dumbbell Rows', false, 2, 'single-arm-dumbbell-rows', false),
    ('Single Arm Lat Pulldowns', false, 2, 'single-arm-lat-pulldowns', false),
    ('Machine Horizontal Rows', false, 2, 'machine-horizontal-rows', false),
    ('Single Arm Cable Rows', false, 2, 'single-arm-cable-rows', false),
    ('Wide Grip Seated Cable Rows', false, 2, 'wide-grip-seated-cable-rows', false),
    ('Seated Machine Rows', false, 2, 'seated-machine-rows', false),
-- Shoulders
    ('Overhead Press', false, 3, 'overhead-press', false),
    ('Dumbbell Lateral Raises', false, 3, 'dumbbell-lateral-raises', false),
    ('Front Raises', false, 3, 'front-raises', false),
    ('Rear Delt Flyes', false, 3, 'rear-delt-flyes', false),
    ('Arnold Press', false, 3, 'arnold-press', false),
    ('Dumbbell Shoulder Press', false, 3, 'dumbbell-shoulder-press', false),
    ('Cable Lateral Raises', false, 3, 'cable-lateral-raises', false),
    ('Face Pulls', false, 3, 'face-pulls', false),
    ('Upright Rows', false, 3, 'upright-rows', false),
-- Biceps
    ('Barbell Curls', false, 4, 'barbell-curls', false),
    ('Hammer Curls', false, 4, 'hammer-curls', false),
    ('Preacher Curls', false, 4, 'preacher-curls', false),
    ('Concentration Curls', false, 4, 'concentration-curls', false),
    ('Cable Curls', false, 4, 'cable-curls', false),
    ('Incline Dumbbell Curls', false, 4, 'incline-dumbbell-curls', false),
    ('Zottman Curls', false, 4, 'zottman-curls', false),
    ('Bayesian Curls', false, 4, 'bayesian-curls', false),
    ('EZ Bar Curls', false, 4, 'ez-bar-curls', false),
    ('Dumbbell Curls', false, 4, 'dumbbell-curls', false),
    ('Machine Preacher Curls', false, 4, 'machine-preacher-curls', false),

-- Triceps
    ('Pushdowns', false, 5, 'pushdowns', false),
    ('Overhead Extensions', false, 5, 'overhead-extensions', false),
    ('Skullcrusher', false, 5, 'skullcrusher', false),
    ('Dips', true, 5, 'dips', false),
    ('Close-Grip Bench Press', false, 5, 'close-grip-bench-press', false),
    ('Kickbacks', false, 5, 'kickbacks', false),
    ('Diamond Push-Ups', true, 5, 'diamond-push-ups', false),
    ('Cable Rope Pushdowns', false, 5, 'cable-rope-pushdowns', false),
-- Quads
    ('Squats', false, 6, 'squats', false),
    ('Leg Press', false, 6, 'leg-press', false),
    ('Bulgarian Split Squats', false, 6, 'bulgarian-split-squats', false),
    ('Front Squats', false, 6, 'front-squats', false),
    ('Leg Press Machine', false, 6, 'leg-press-machine', false),
    ('Step-Ups', true, 6, 'step-ups', false),
    ('Leg Extensions', false, 6, 'leg-extensions', false),
    ('Smith Machine Squats', false, 6, 'smith-machine-squats', false),
    ('Goblet Squats', false, 6, 'goblet-squats', false),
    ('Hack Squats', false, 6, 'hack-squats', false),
    ('Sissy Squats', true, 6, 'sissy-squats', false),
    ('Adductor Machine', false, 6, 'adductor-machine', false),
-- Hamstrings
    ('Deadlift', false, 7, 'deadlift', false),
    ('Romanian Deadlift', false, 7, 'romanian-deadlift', false),
    ('Seated Leg Curls', false, 7, 'seated-leg-curls', false),
    ('Lying Leg Curls', false, 7, 'lying-leg-curls', false),
    ('Glute-Ham Raises', false, 7, 'glute-ham-raises', false),
    ('Good Mornings', false, 7, 'good-mornings', false),
    ('Kettlebell Swings', false, 7, 'kettlebell-swings', false),
    ('Nordic Curls', false, 7, 'nordic-curls', false),
    ('Stiff-Legged Deadlifts', false, 7, 'stiff-legged-deadlifts', false),
-- Glutes
    ('Hip Thrusts', false, 8, 'hip-thrusts', false),
    ('Glute Bridges', false, 8, 'glute-bridges', false),
    ('Cable Kickbacks', false, 8, 'cable-kickbacks', false),
    ('Lunges', false, 8, 'lunges', false),
    ('Abductor Machine', false, 8, 'abductor-machine', false),
-- Abs
    ('Crunches', true, 9, 'crunches', false),
    ('Hanging Leg Raises', true, 9, 'hanging-leg-raises', false),
    ('Plank', true, 9, 'plank', true),
    ('Cable Crunches', false, 9, 'cable-crunches', false),
    ('Russian Twists', true, 9, 'russian-twists', false),
    ('Decline Crunches', true, 9, 'decline-crunches', false),
-- Calves
    ('Machine Calf Raises', false, 10, 'calf-raises', false),
    ('Standing Calf Raises', true, 10, 'standing-calf-raises', false),
    ('Smith Machine Calf Raises', false, 10, 'smith-machine-calf-raises', false),
-- Forearms
    ('Wrist Curls', false, 11, 'wrist-curls', false),
    ('Reverse Curls', false, 11, 'reverse-curls', false),
-- Traps
    ('Dumbbell Shrugs', false, 12, 'dumbbell-shrugs', false),
    ('Farmer`s Walk', false, 12, 'farmers-walk', false)

ON CONFLICT DO NOTHING;