const APP_VERSION = "Beta 0.1.0";

const PRIVACY_POLICY_VERSION = "1.0";
const HEALTH_DATA_POLICY_VERSION = "1.0";
const AI_CHAT_CONSENT_VERSION = "1.0";
const TERMS_AND_CONDITIONS_VERSION = "1.0";

export {
  APP_VERSION,
  PRIVACY_POLICY_VERSION,
  HEALTH_DATA_POLICY_VERSION,
  AI_CHAT_CONSENT_VERSION,
  TERMS_AND_CONDITIONS_VERSION,
};
